import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import '../styles/Introduction.css';
import experience from '../images/experience.png';
import projects from '../images/projects.png';
import resume from '../images/resume.png';
import more from '../images/more.png';
import me from '../images/me.jpg';
const Introduction = () => {
    return (_jsxs("div", { id: "introduction", className: "section introduction-main-container", children: [_jsxs("div", { className: "introduction-section-text", children: [_jsxs("div", { className: "main-heading", children: ["Hi! My name is ", _jsx("span", { className: "main-heading-highlight", children: "Angkitha" }), "."] }), _jsx("div", { className: "second-heading", children: "Software Engineer" }), _jsx("div", { className: "third-heading", children: "Seeking roles in Data Analytics/Embedded Engineering." }), _jsxs("div", { className: "description-box", children: ["I graduated June 2024 from University of California, San Diego with a Bachelor's in Electrical and Computer Engineering with a focus in Machine Learning and Control Theory. I minored in Cognitive Science. I've participated in numerous professional and academic projects that demonstrate my prowess in generating ML models used to further data analysis and visualization; the majority I've accomplished using ", _jsx("span", { className: "description-highlight", children: "Python" }), ", ", _jsx("span", { className: "description-highlight", children: "SQL" }), ", ", _jsx("span", { className: "description-highlight", children: "MATLAB" }), ", and ", _jsx("span", { className: "description-highlight", children: "Verilog" }), ".", _jsx("p", {}), "Currently, I am working at ", _jsx("span", { className: "description-highlight", children: "L3Harris Technologies" }), " as a Software Engineer. I work to deliver efficient test engineering solutions that meet the standards of the client my team collaborates with. The majority of my work has refined my programming skills in ", _jsx("span", { className: "description-highlight", children: "C++ " }), " and Verilog.", _jsx("p", {}), "In my free time, I enjoy partaking in ", _jsx("span", { className: "description-highlight", children: "front-end development projects" }), " (such as this portfolio), working out/running, listening to music, and exploring food venues. Please navigate through my portfolio using the interactive vinyls to the left."] })] }), _jsxs("div", { className: "introduction-section-vinyls", children: [_jsx("img", { src: me, alt: "Personal Image", className: "turnTable-base" }), _jsxs("div", { className: "vinyl-chain", children: [_jsx("a", { href: "#experience", className: "vinyl-link", id: "vinyl-1", children: _jsx("img", { src: experience, alt: "Experience", className: "vinyl-image" }) }), _jsx("a", { href: "#projects", className: "vinyl-link", id: "vinyl-2", children: _jsx("img", { src: projects, alt: "Projects", className: "vinyl-image" }) }), _jsx("a", { href: "#resume", className: "vinyl-link", id: "vinyl-3", children: _jsx("img", { src: resume, alt: "Resume", className: "vinyl-image" }) }), _jsx("a", { href: "#resume", className: "vinyl-link", id: "vinyl-4", children: _jsx("img", { src: more, alt: "More", className: "vinyl-image" }) })] }), _jsx("div", { className: "vinyl-holder" })] })] }));
};
export default Introduction;
